/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,ts,tsx}', './components/**/*.{js,ts,tsx}'],

  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Satoshi-Regular'],
        mono: ['SF Mono'],
        satoshi: ['Satoshi-Regular'],
        'Satoshi-Light': ['Satoshi-Light'],
        'Satoshi-Regular': ['Satoshi-Regular'],
        'Satoshi-Medium': ['Satoshi-Medium'],
        'Satoshi-Bold': ['Satoshi-Bold'],
        'Satoshi-Black': ['Satoshi-Black'],
      },
      fontSize: {
        label2: ['var(--text-label2)', { lineHeight: 'var(--leading-normal)' }],
        label1: ['var(--text-label1)', { lineHeight: 'var(--leading-normal)' }],
        paragraph2: ['var(--text-paragraph2)', { lineHeight: 'var(--leading-normal)' }],
        paragraph1: ['var(--text-paragraph1)', { lineHeight: 'var(--leading-normal)' }],
        subheading2: ['var(--text-subheading2)', { lineHeight: 'var(--leading-normal)' }],
        subheading1: ['var(--text-subheading1)', { lineHeight: 'var(--leading-normal)' }],
        heading4: ['var(--text-heading4)', { lineHeight: 'var(--leading-snug)' }],
        heading3: ['var(--text-heading3)', { lineHeight: 'var(--leading-snug)' }],
        heading2: ['var(--text-heading2)', { lineHeight: 'var(--leading-tight)' }],
        heading1: ['var(--text-heading1)', { lineHeight: 'var(--leading-tight)' }],
        display3: ['var(--text-display3)', { lineHeight: 'var(--leading-tight)' }],
        display2: ['var(--text-display2)', { lineHeight: 'var(--leading-tight)' }],
        display1: ['var(--text-display1)', { lineHeight: 'var(--leading-tight)' }],
      },
      fontWeight: {
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
      lineHeight: {
        none: 'var(--leading-none)',
        tight: 'var(--leading-tight)',
        snug: 'var(--leading-snug)',
        normal: 'var(--leading-normal)',
        relaxed: 'var(--leading-relaxed)',
        loose: 'var(--leading-loose)',
      },
      letterSpacing: {
        tighter: 'var(--tracking-tighter)',
        tight: 'var(--tracking-tight)',
        normal: 'var(--tracking-normal)',
        wide: 'var(--tracking-wide)',
        wider: 'var(--tracking-wider)',
        widest: 'var(--tracking-widest)',
      },
      colors: {
        primary: {
          50: 'rgb(var(--primary-50) / <alpha-value>)',
          100: 'rgb(var(--primary-100) / <alpha-value>)',
          200: 'rgb(var(--primary-200) / <alpha-value>)',
          300: 'rgb(var(--primary-300) / <alpha-value>)',
          400: 'rgb(var(--primary-400) / <alpha-value>)',
          500: 'rgb(var(--primary-500) / <alpha-value>)',
          600: 'rgb(var(--primary-600) / <alpha-value>)',
          700: 'rgb(var(--primary-700) / <alpha-value>)',
          800: 'rgb(var(--primary-800) / <alpha-value>)',
          900: 'rgb(var(--primary-900) / <alpha-value>)',
          950: 'rgb(var(--primary-950) / <alpha-value>)',
        },
        surface: {
          100: 'rgb(var(--surface-100) / <alpha-value>)',
          200: 'rgb(var(--surface-200) / <alpha-value>)',
          300: 'rgb(var(--surface-300) / <alpha-value>)',
          400: 'rgb(var(--surface-400) / <alpha-value>)',
          500: 'rgb(var(--surface-500) / <alpha-value>)',
          600: 'rgb(var(--surface-600) / <alpha-value>)',
        },
        background: {
          100: 'rgb(var(--background-100) / <alpha-value>)',
          200: 'rgb(var(--background-200) / <alpha-value>)',
          300: 'rgb(var(--background-300) / <alpha-value>)',
          400: 'rgb(var(--background-400) / <alpha-value>)',
          500: 'rgb(var(--background-500) / <alpha-value>)',
          600: 'rgb(var(--background-600) / <alpha-value>)',
        },
        neutral: {
          100: 'rgb(var(--neutral-100) / <alpha-value>)',
          200: 'rgb(var(--neutral-200) / <alpha-value>)',
          300: 'rgb(var(--neutral-300) / <alpha-value>)',
          400: 'rgb(var(--neutral-400) / <alpha-value>)',
          500: 'rgb(var(--neutral-500) / <alpha-value>)',
          600: 'rgb(var(--neutral-600) / <alpha-value>)',
        },
        success: {
          50: 'rgb(var(--success-50) / <alpha-value>)',
          100: 'rgb(var(--success-100) / <alpha-value>)',
          200: 'rgb(var(--success-200) / <alpha-value>)',
          300: 'rgb(var(--success-300) / <alpha-value>)',
          400: 'rgb(var(--success-400) / <alpha-value>)',
          500: 'rgb(var(--success-500) / <alpha-value>)',
          600: 'rgb(var(--success-600) / <alpha-value>)',
          700: 'rgb(var(--success-700) / <alpha-value>)',
          800: 'rgb(var(--success-800) / <alpha-value>)',
          900: 'rgb(var(--success-900) / <alpha-value>)',
          950: 'rgb(var(--success-950) / <alpha-value>)',
        },
        info: {
          50: 'rgb(var(--info-50) / <alpha-value>)',
          100: 'rgb(var(--info-100) / <alpha-value>)',
          200: 'rgb(var(--info-200) / <alpha-value>)',
          300: 'rgb(var(--info-300) / <alpha-value>)',
          400: 'rgb(var(--info-400) / <alpha-value>)',
          500: 'rgb(var(--info-500) / <alpha-value>)',
          600: 'rgb(var(--info-600) / <alpha-value>)',
          700: 'rgb(var(--info-700) / <alpha-value>)',
          800: 'rgb(var(--info-800) / <alpha-value>)',
          900: 'rgb(var(--info-900) / <alpha-value>)',
          950: 'rgb(var(--info-950) / <alpha-value>)',
        },
        warning: {
          50: 'rgb(var(--warning-50) / <alpha-value>)',
          100: 'rgb(var(--warning-100) / <alpha-value>)',
          200: 'rgb(var(--warning-200) / <alpha-value>)',
          300: 'rgb(var(--warning-300) / <alpha-value>)',
          400: 'rgb(var(--warning-400) / <alpha-value>)',
          500: 'rgb(var(--warning-500) / <alpha-value>)',
          600: 'rgb(var(--warning-600) / <alpha-value>)',
          700: 'rgb(var(--warning-700) / <alpha-value>)',
          800: 'rgb(var(--warning-800) / <alpha-value>)',
          900: 'rgb(var(--warning-900) / <alpha-value>)',
          950: 'rgb(var(--warning-950) / <alpha-value>)',
        },
        danger: {
          50: 'rgb(var(--danger-50) / <alpha-value>)',
          100: 'rgb(var(--danger-100) / <alpha-value>)',
          200: 'rgb(var(--danger-200) / <alpha-value>)',
          300: 'rgb(var(--danger-300) / <alpha-value>)',
          400: 'rgb(var(--danger-400) / <alpha-value>)',
          500: 'rgb(var(--danger-500) / <alpha-value>)',
          600: 'rgb(var(--danger-600) / <alpha-value>)',
          700: 'rgb(var(--danger-700) / <alpha-value>)',
          800: 'rgb(var(--danger-800) / <alpha-value>)',
          900: 'rgb(var(--danger-900) / <alpha-value>)',
          950: 'rgb(var(--danger-950) / <alpha-value>)',
        },
        secondary: {
          50: 'rgb(var(--secondary-50) / <alpha-value>)',
          100: 'rgb(var(--secondary-100) / <alpha-value>)',
          200: 'rgb(var(--secondary-200) / <alpha-value>)',
          300: 'rgb(var(--secondary-300) / <alpha-value>)',
          400: 'rgb(var(--secondary-400) / <alpha-value>)',
          500: 'rgb(var(--secondary-500) / <alpha-value>)',
          600: 'rgb(var(--secondary-600) / <alpha-value>)',
          700: 'rgb(var(--secondary-700) / <alpha-value>)',
          800: 'rgb(var(--secondary-800) / <alpha-value>)',
          900: 'rgb(var(--secondary-900) / <alpha-value>)',
          950: 'rgb(var(--secondary-950) / <alpha-value>)',
        },
        tertiary: {
          50: 'rgb(var(--tertiary-50) / <alpha-value>)',
          100: 'rgb(var(--tertiary-100) / <alpha-value>)',
          200: 'rgb(var(--tertiary-200) / <alpha-value>)',
          300: 'rgb(var(--tertiary-300) / <alpha-value>)',
          400: 'rgb(var(--tertiary-400) / <alpha-value>)',
          500: 'rgb(var(--tertiary-500) / <alpha-value>)',
          600: 'rgb(var(--tertiary-600) / <alpha-value>)',
          700: 'rgb(var(--tertiary-700) / <alpha-value>)',
          800: 'rgb(var(--tertiary-800) / <alpha-value>)',
          900: 'rgb(var(--tertiary-900) / <alpha-value>)',
          950: 'rgb(var(--tertiary-950) / <alpha-value>)',
        },
      },
    },
  },
  plugins: [],
};
